
# Build settings
name: efraimgentil.github.io
description: Just for Fun

#markdown: redcarpet
#markdown: kramdown
#highlighter: pygments

logo: false
paginate: 5
paginate_path: "/posts/:num/"

# Details for the RSS feed generator
url:       '???'
author:    'Efraim Gentil'
permalink: /post/:categories/:title
archive: false
disqus: false

baseurl: "" 

languages: ["pt_BR", "en"]

exclude_from_localizations: ["Gemfile" 
, "Gemfile.lock"
 ,"assets"
 , "javascript"
 , "images"
 , "css"
 , "build.py" 
 , "mail"
 , "tocommit"
 , "LICENSE"
 , "README.md"
 , "gulpfile.js"]



gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
  - redcarpet

