version: "3"
services: 
  blog:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    networks:
      - my_net
    #depends_on:
      # - someservice
networks:
  my_net:
    driver: bridge